# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/latho12/git/DM818-Mandatory-Assignment-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/latho12/git/DM818-Mandatory-Assignment-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/latho12/git/DM818-Mandatory-Assignment-2/CMakeFiles /home/latho12/git/DM818-Mandatory-Assignment-2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/latho12/git/DM818-Mandatory-Assignment-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dm818_base_serial

# Build rule for target.
dm818_base_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dm818_base_serial
.PHONY : dm818_base_serial

# fast build rule for target.
dm818_base_serial/fast:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/build
.PHONY : dm818_base_serial/fast

#=============================================================================
# Target rules for targets named dm818_serial

# Build rule for target.
dm818_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dm818_serial
.PHONY : dm818_serial

# fast build rule for target.
dm818_serial/fast:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/build
.PHONY : dm818_serial/fast

#=============================================================================
# Target rules for targets named dm818_test

# Build rule for target.
dm818_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dm818_test
.PHONY : dm818_test

# fast build rule for target.
dm818_test/fast:
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/build
.PHONY : dm818_test/fast

#=============================================================================
# Target rules for targets named mpi

# Build rule for target.
mpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi
.PHONY : mpi

# fast build rule for target.
mpi/fast:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/build
.PHONY : mpi/fast

mpi-other/source/common.o: mpi-other/source/common.cpp.o
.PHONY : mpi-other/source/common.o

# target to build an object file
mpi-other/source/common.cpp.o:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/common.cpp.o
.PHONY : mpi-other/source/common.cpp.o

mpi-other/source/common.i: mpi-other/source/common.cpp.i
.PHONY : mpi-other/source/common.i

# target to preprocess a source file
mpi-other/source/common.cpp.i:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/common.cpp.i
.PHONY : mpi-other/source/common.cpp.i

mpi-other/source/common.s: mpi-other/source/common.cpp.s
.PHONY : mpi-other/source/common.s

# target to generate assembly for a file
mpi-other/source/common.cpp.s:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/common.cpp.s
.PHONY : mpi-other/source/common.cpp.s

mpi-other/source/grid.o: mpi-other/source/grid.cpp.o
.PHONY : mpi-other/source/grid.o

# target to build an object file
mpi-other/source/grid.cpp.o:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/grid.cpp.o
.PHONY : mpi-other/source/grid.cpp.o

mpi-other/source/grid.i: mpi-other/source/grid.cpp.i
.PHONY : mpi-other/source/grid.i

# target to preprocess a source file
mpi-other/source/grid.cpp.i:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/grid.cpp.i
.PHONY : mpi-other/source/grid.cpp.i

mpi-other/source/grid.s: mpi-other/source/grid.cpp.s
.PHONY : mpi-other/source/grid.s

# target to generate assembly for a file
mpi-other/source/grid.cpp.s:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/grid.cpp.s
.PHONY : mpi-other/source/grid.cpp.s

mpi-other/source/mpi.o: mpi-other/source/mpi.cpp.o
.PHONY : mpi-other/source/mpi.o

# target to build an object file
mpi-other/source/mpi.cpp.o:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/mpi.cpp.o
.PHONY : mpi-other/source/mpi.cpp.o

mpi-other/source/mpi.i: mpi-other/source/mpi.cpp.i
.PHONY : mpi-other/source/mpi.i

# target to preprocess a source file
mpi-other/source/mpi.cpp.i:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/mpi.cpp.i
.PHONY : mpi-other/source/mpi.cpp.i

mpi-other/source/mpi.s: mpi-other/source/mpi.cpp.s
.PHONY : mpi-other/source/mpi.s

# target to generate assembly for a file
mpi-other/source/mpi.cpp.s:
	$(MAKE) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi-other/source/mpi.cpp.s
.PHONY : mpi-other/source/mpi.cpp.s

serial-other/source/common.o: serial-other/source/common.cpp.o
.PHONY : serial-other/source/common.o

# target to build an object file
serial-other/source/common.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/common.cpp.o
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/common.cpp.o
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/common.cpp.o
.PHONY : serial-other/source/common.cpp.o

serial-other/source/common.i: serial-other/source/common.cpp.i
.PHONY : serial-other/source/common.i

# target to preprocess a source file
serial-other/source/common.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/common.cpp.i
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/common.cpp.i
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/common.cpp.i
.PHONY : serial-other/source/common.cpp.i

serial-other/source/common.s: serial-other/source/common.cpp.s
.PHONY : serial-other/source/common.s

# target to generate assembly for a file
serial-other/source/common.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/common.cpp.s
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/common.cpp.s
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/common.cpp.s
.PHONY : serial-other/source/common.cpp.s

serial-other/source/grid.o: serial-other/source/grid.cpp.o
.PHONY : serial-other/source/grid.o

# target to build an object file
serial-other/source/grid.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/grid.cpp.o
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/grid.cpp.o
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/grid.cpp.o
.PHONY : serial-other/source/grid.cpp.o

serial-other/source/grid.i: serial-other/source/grid.cpp.i
.PHONY : serial-other/source/grid.i

# target to preprocess a source file
serial-other/source/grid.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/grid.cpp.i
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/grid.cpp.i
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/grid.cpp.i
.PHONY : serial-other/source/grid.cpp.i

serial-other/source/grid.s: serial-other/source/grid.cpp.s
.PHONY : serial-other/source/grid.s

# target to generate assembly for a file
serial-other/source/grid.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/grid.cpp.s
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/grid.cpp.s
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/grid.cpp.s
.PHONY : serial-other/source/grid.cpp.s

serial-other/source/serial.o: serial-other/source/serial.cpp.o
.PHONY : serial-other/source/serial.o

# target to build an object file
serial-other/source/serial.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial.cpp.o
.PHONY : serial-other/source/serial.cpp.o

serial-other/source/serial.i: serial-other/source/serial.cpp.i
.PHONY : serial-other/source/serial.i

# target to preprocess a source file
serial-other/source/serial.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial.cpp.i
.PHONY : serial-other/source/serial.cpp.i

serial-other/source/serial.s: serial-other/source/serial.cpp.s
.PHONY : serial-other/source/serial.s

# target to generate assembly for a file
serial-other/source/serial.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial.cpp.s
.PHONY : serial-other/source/serial.cpp.s

serial-other/source/serial_base.o: serial-other/source/serial_base.cpp.o
.PHONY : serial-other/source/serial_base.o

# target to build an object file
serial-other/source/serial_base.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base.cpp.o
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_base.cpp.o
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/serial_base.cpp.o
.PHONY : serial-other/source/serial_base.cpp.o

serial-other/source/serial_base.i: serial-other/source/serial_base.cpp.i
.PHONY : serial-other/source/serial_base.i

# target to preprocess a source file
serial-other/source/serial_base.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base.cpp.i
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_base.cpp.i
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/serial_base.cpp.i
.PHONY : serial-other/source/serial_base.cpp.i

serial-other/source/serial_base.s: serial-other/source/serial_base.cpp.s
.PHONY : serial-other/source/serial_base.s

# target to generate assembly for a file
serial-other/source/serial_base.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base.cpp.s
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_base.cpp.s
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/serial_base.cpp.s
.PHONY : serial-other/source/serial_base.cpp.s

serial-other/source/serial_base_main.o: serial-other/source/serial_base_main.cpp.o
.PHONY : serial-other/source/serial_base_main.o

# target to build an object file
serial-other/source/serial_base_main.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base_main.cpp.o
.PHONY : serial-other/source/serial_base_main.cpp.o

serial-other/source/serial_base_main.i: serial-other/source/serial_base_main.cpp.i
.PHONY : serial-other/source/serial_base_main.i

# target to preprocess a source file
serial-other/source/serial_base_main.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base_main.cpp.i
.PHONY : serial-other/source/serial_base_main.cpp.i

serial-other/source/serial_base_main.s: serial-other/source/serial_base_main.cpp.s
.PHONY : serial-other/source/serial_base_main.s

# target to generate assembly for a file
serial-other/source/serial_base_main.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_base_serial.dir/build.make CMakeFiles/dm818_base_serial.dir/serial-other/source/serial_base_main.cpp.s
.PHONY : serial-other/source/serial_base_main.cpp.s

serial-other/source/serial_main.o: serial-other/source/serial_main.cpp.o
.PHONY : serial-other/source/serial_main.o

# target to build an object file
serial-other/source/serial_main.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_main.cpp.o
.PHONY : serial-other/source/serial_main.cpp.o

serial-other/source/serial_main.i: serial-other/source/serial_main.cpp.i
.PHONY : serial-other/source/serial_main.i

# target to preprocess a source file
serial-other/source/serial_main.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_main.cpp.i
.PHONY : serial-other/source/serial_main.cpp.i

serial-other/source/serial_main.s: serial-other/source/serial_main.cpp.s
.PHONY : serial-other/source/serial_main.s

# target to generate assembly for a file
serial-other/source/serial_main.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_serial.dir/build.make CMakeFiles/dm818_serial.dir/serial-other/source/serial_main.cpp.s
.PHONY : serial-other/source/serial_main.cpp.s

serial-other/source/test_suite.o: serial-other/source/test_suite.cpp.o
.PHONY : serial-other/source/test_suite.o

# target to build an object file
serial-other/source/test_suite.cpp.o:
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/test_suite.cpp.o
.PHONY : serial-other/source/test_suite.cpp.o

serial-other/source/test_suite.i: serial-other/source/test_suite.cpp.i
.PHONY : serial-other/source/test_suite.i

# target to preprocess a source file
serial-other/source/test_suite.cpp.i:
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/test_suite.cpp.i
.PHONY : serial-other/source/test_suite.cpp.i

serial-other/source/test_suite.s: serial-other/source/test_suite.cpp.s
.PHONY : serial-other/source/test_suite.s

# target to generate assembly for a file
serial-other/source/test_suite.cpp.s:
	$(MAKE) -f CMakeFiles/dm818_test.dir/build.make CMakeFiles/dm818_test.dir/serial-other/source/test_suite.cpp.s
.PHONY : serial-other/source/test_suite.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dm818_base_serial"
	@echo "... dm818_serial"
	@echo "... dm818_test"
	@echo "... edit_cache"
	@echo "... mpi"
	@echo "... rebuild_cache"
	@echo "... mpi-other/source/common.o"
	@echo "... mpi-other/source/common.i"
	@echo "... mpi-other/source/common.s"
	@echo "... mpi-other/source/grid.o"
	@echo "... mpi-other/source/grid.i"
	@echo "... mpi-other/source/grid.s"
	@echo "... mpi-other/source/mpi.o"
	@echo "... mpi-other/source/mpi.i"
	@echo "... mpi-other/source/mpi.s"
	@echo "... serial-other/source/common.o"
	@echo "... serial-other/source/common.i"
	@echo "... serial-other/source/common.s"
	@echo "... serial-other/source/grid.o"
	@echo "... serial-other/source/grid.i"
	@echo "... serial-other/source/grid.s"
	@echo "... serial-other/source/serial.o"
	@echo "... serial-other/source/serial.i"
	@echo "... serial-other/source/serial.s"
	@echo "... serial-other/source/serial_base.o"
	@echo "... serial-other/source/serial_base.i"
	@echo "... serial-other/source/serial_base.s"
	@echo "... serial-other/source/serial_base_main.o"
	@echo "... serial-other/source/serial_base_main.i"
	@echo "... serial-other/source/serial_base_main.s"
	@echo "... serial-other/source/serial_main.o"
	@echo "... serial-other/source/serial_main.i"
	@echo "... serial-other/source/serial_main.s"
	@echo "... serial-other/source/test_suite.o"
	@echo "... serial-other/source/test_suite.i"
	@echo "... serial-other/source/test_suite.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

